version: 2
updates:
  # Maintain Backend Dependencies (Maven)
  - package-ecosystem: "maven"
    directory: "/backend"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10

  # Maintain Frontend Dependencies (NPM)
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10

  # Maintain Docker Base Images
  - package-ecosystem: "docker"
    directory: "/backend"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/nginx"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/frontend"
    schedule:
      interval: "daily"

  # Maintain GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
