services:
  postgres:
    image: postgres:15-alpine
    container_name: ares-postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: ares-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  mailhog:
    image: mailhog/mailhog
    container_name: ares-mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
  nginx:
    build: ./nginx
    container_name: ares-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/certs:/etc/nginx/certs:ro
    environment:
      HOST: ${HOST}
      SSL_CERT_PATH: ${SSL_CERT_PATH}
      SSL_KEY_PATH: ${SSL_KEY_PATH}
    depends_on:
      - frontend
      - backend

  backend:
    build: ./backend
    container_name: ares-backend
    volumes:
      - ./logs:/app/logs
    restart: always
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      ACTIVE_PROFILE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_DATA_REDIS_HOST: redis
      SPRING_MAIL_HOST: ${SPRING_MAIL_HOST}
      SPRING_MAIL_PORT: ${SPRING_MAIL_PORT}
      #SPRING_MAIL_USERNAME: ${SPRING_MAIL_USERNAME}
      #SPRING_MAIL_PASSWORD: ${SPRING_MAIL_PASSWORD}
      SPRING_MAIL_SMTP_AUTH: "false"
      SPRING_MAIL_SMTP_STARTTLS_ENABLE: "false"
      JWT_SECRET: ${JWT_SECRET}
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}
      ARES_ADMIN_EMAIL: ${ARES_ADMIN_EMAIL}
      ARES_ADMIN_PASSWORD: ${ARES_ADMIN_PASSWORD}
      FRONTEND_URL: ${FRONTEND_URL}
      GH_CLIENT_ID: ${GH_CLIENT_ID}
      GH_SECRET: ${GH_SECRET}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_SECRET: ${GOOGLE_SECRET}
      FACEBOOK_CLIENT_ID: ${FACEBOOK_CLIENT_ID}
      FACEBOOK_SECRET: ${FACEBOOK_SECRET}
    depends_on:
      - postgres
      - redis
      - mailhog

  frontend:
    build: ./frontend
    container_name: ares-frontend
    restart: always
    ports:
      - "4200:4000"
    environment:
      PORT: 4000
      BACKEND_URL: http://backend:8080
    depends_on:
      - backend

volumes:
  postgres_data:
  redis_data:
