services:
  postgres:
    image: postgres:15-alpine
    container_name: ares-postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "127.0.0.1:5432:5432" # Only accessible via SSH tunnel or localhost
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: ares-redis
    restart: always
    volumes:
      - redis_data:/data

  nginx:
    image: ${IMAGE_REPO}/nginx:latest
    build: ./nginx
    container_name: ares-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/certs:/etc/nginx/certs:ro

  backend:
    image: ${IMAGE_REPO}/backend:latest
    build: ./backend
    container_name: ares-backend
    volumes:
      - ./logs:/app/logs
    restart: always
    environment:
      ACTIVE_PROFILE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_DATA_REDIS_HOST: redis
      SPRING_MAIL_HOST: ${SPRING_MAIL_HOST}
      SPRING_MAIL_PORT: ${SPRING_MAIL_PORT}
      SPRING_MAIL_USERNAME: ${SPRING_MAIL_USERNAME}
      SPRING_MAIL_PASSWORD: ${SPRING_MAIL_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}
      ARES_ADMIN_EMAIL: ${ARES_ADMIN_EMAIL}
      ARES_ADMIN_PASSWORD: ${ARES_ADMIN_PASSWORD}
      FRONTEND_URL: ${FRONTEND_URL}
      GH_CLIENT_ID: ${GH_CLIENT_ID}
      GH_SECRET: ${GH_SECRET}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_SECRET: ${GOOGLE_SECRET}
      FACEBOOK_CLIENT_ID: ${FACEBOOK_CLIENT_ID}
      FACEBOOK_SECRET: ${FACEBOOK_SECRET}


    depends_on:
      - postgres
      - redis

  frontend:
    image: ${IMAGE_REPO}/frontend:latest
    build: ./frontend
    container_name: ares-frontend
    restart: always
    environment:
      PORT: 4000
      BACKEND_URL: http://backend:8080
    depends_on:
      - backend

volumes:
  postgres_data:
  redis_data:
