spring:
  application:
    name: Ares
    allowedOrigins: ${ALLOWED_ORIGINS}
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: ${GH_CLIENT_ID}
            clientSecret: ${GH_SECRET}
          google:
            clientId: ${GOOGLE_CLIENT_ID}
            clientSecret: ${GOOGLE_SECRET}
            scope:
              - email
              - profile
          facebook:
            clientId: ${FACEBOOK_CLIENT_ID}
            clientSecret: ${FACEBOOK_SECRET}
            scope:
              - email
              - public_profile
  profiles:
    active: ${ACTIVE_PROFILE}
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  sql:
    init:
      mode: never
  data:
    redis:
      host: redis
      port: 6379
  mail:
    host: ${SPRING_MAIL_HOST:localhost}
    port: ${SPRING_MAIL_PORT:1025}
    username: ${SPRING_MAIL_USERNAME:}
    password: ${SPRING_MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: ${SPRING_MAIL_SMTP_AUTH:true}
          starttls:
            enable: ${SPRING_MAIL_SMTP_STARTTLS_ENABLE:true}
  flyway:
    enabled: true
    baseline-on-migrate: false # Set to false since DB is empty
    locations: classpath:db/migration
    placeholders:
      ADMIN_EMAIL: ${ARES_ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ARES_ADMIN_PASSWORD}
      TEST_USER1_EMAIL: ${ARES_TEST_USER1}
      TEST_USER1_PW: ${ARES_TEST_USER_PW1}
      TEST_USER2_EMAIL: ${ARES_TEST_USER2}
      TEST_USER2_PW:  ${ARES_TEST_USER_PW2}
      TEST_USER3_EMAIL: ${ARES_TEST_USER3}
      TEST_USER3_PW:  ${ARES_TEST_USER_PW3}

server:
  forward-headers-strategy: native

app:
  frontend:
    url: ${FRONTEND_URL}
  copyright:
    start-year: 2024

togglz:
  console:
    path: /features
    secured: false

user:
  password:
    min_length: 8
feed:
  interval_ms: 300000 # 5 min
  query_limit: 1000

security:
  jwt:
    secret: ${JWT_SECRET}
    refresh_expiration_ms: 86400000 # 24 hr
    access_expiration_ms: 3600000  # 1 hour

logging:
  file:
    path: ./logs
    name: ${logging.file.path}/${spring.application.name}.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 7
      file-name-pattern: ${logging.file.path}/archived/${spring.application.name}-%d{yyyy-MM-dd}-%i.log.gz
  level:
    root: INFO
    net.blackhacker.ares: ${LOG_LEVEL:DEBUG}
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.hibernate.SQL: ${SQL_LOG_LEVEL:INFO}
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
